import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainLayout from "../components/MainLayout";
import {Spin} from "antd";

export default function Home({setIsLoading, isLoading}) {

    React.useEffect(() => {
        setIsLoading(false)
    }, [])


    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
          <MainLayout isLoading={isLoading} setIsLoading={setIsLoading} >
              <h1>40340430</h1>
              {isLoading ? <h1>Is loading</h1> : null}
              <button onClick={()=>setIsLoading (!isLoading)}>123</button>
          </MainLayout>
      </div>
    </div>
  )
}
